# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  #schedule:
   # - cron: '*/20 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute babashka script
        uses: tzafrirben/babashka-docker-action@v1
        with:
          bb_src: generate.clj
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
